name: Pull Request Checking

on: 
  push:   
    branches:
      - feature/** # Branches que se iniciam com feature/...

jobs:

  check-formatting: # Este espaço pode receber qualquer nome. Será o nome que aparecerá na esteira
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # GitHub Action used in workflows to check out your repository's code so subsequent steps in the workflow can access the files in it. It is like a download of the files.

        # Uso de custom actions como parte de um job. Útil para tarefas repetitivas ao longo do código
        # Sempre use abaixo do checkout
      - name: Load and Cache Dependencies
        id: cache-deps
        uses: ./.github/actions/cached_dependencies # Não é necessário apontar o arquivo neste caso. O Github sempre vai buscar o arquivo actions.yml no prefixo informado.
        with:
          caching: 'true' #Passa essa variável como input para a custom action
      
      - name: Begin
        run: echo "Beginning to check code formatting"

      - name: Set up Python
        uses: actions/setup-python@v4 # Instalar a linguagem que se deseja usar. Neste caso, Python
        with:
          python-version: '3.12'  # or any version you need
      
      - name: Run Black (check only)
        run: |
          echo "Checando a formatação do código com black"
          black ./app --check
      
      - name: Run Isort (check only)
        run: |
          echo "Checando a ordenação de imports com isort"
          isort ./app --check

      - name: Run Isort (check only)
        run: |
          echo "Checando a estrutura do código com mypy"
          mypy isort ./app --check

  terraform:
    needs: check-formatting
    env:
        AWS_REGION: us-east-1
        ENVIRONMENT: dev

    # Quando se conecta a alguma Cloud, as permissões abaixo precisam ser declaradas
    # Essa declaração ocorre tanto no arquivo principal como nos reusable workflows que são chamados
    permissions:
      id-token: write
      contents: read
    
    name: Terraform Init & Validate
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Assume secrets para conexão com a AWS
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::870256785503:role/github_rodrigo_amandio_role
          aws-region: ${{env.AWS_REGION}}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="inventories/${{ env.ENVIRONMENT }}/terraform.tfvars"

      - name: Terraform Show
        run: terraform show